version: '3.8'

services:
  mysql-server:
    image: mysql:8.0.28
    restart: always
    container_name: mysql-server
    networks:
      net:
        ipv4_address: 12.10.10.2

    command:
     - mysqld
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
        #    volumes:
        # - ./mysql:/var/lib/mysql:rw
    env_file:
     - ./config/db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD

  zabbix-proxy-mysql:
     image: zabbix/zabbix-proxy-mysql:latest
     restart: always
     ports:
      - "10051:10051"
     container_name: zabbix-proxy
     #network_mode: host
     networks:
       net:
         ipv4_address: 12.10.10.3 
     depends_on:
      - mysql-server
     environment:
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix_pwd
      - ZBX_SERVER_HOST=12.10.10.1
      - ZBX_LISTENPORT=10051
      - ZBX_HOSTNAME=zabbix-proxy
      - ZBX_PROXYMODE=1

networks:
  net:
    driver: bridge
    ipam:
       driver: default
       config:
       - subnet: 12.10.10.0/24
         gateway: 12.10.10.1

secrets:
  MYSQL_USER:
    file: ./config/MYSQL_USER
  MYSQL_PASSWORD:
    file: ./config/MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./config/MYSQL_ROOT_PASSWORD
