version: '3.8'

services:
  mysql-server:
    image: mysql:8.0.28
    restart: always
    container_name: mysql-server
    networks:
     - net
    command:
     - mysqld
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
    cap_add:
      - SYS_NICE
    volumes:
     - /home/zabbix/mysql:/var/lib/mysql:rw
    env_file:
     - ./config/db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
 
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest
    networks:
     - net

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    hostname: zabbix-server
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/srv
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-java-gateway
     - zabbix-agent
    networks:
     - net

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
     - "80:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/web
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-server
    networks:
     - net
  
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    hostname: NEOS_ZABBIX_SERVER
    environment:
      - ZBX_SERVER_HOST=zabbix-server
    ports:
     - "10050:10050"
    volumes:
     - /proc:/proc
     - /sys:/sys
     - /dev:/dev
    networks:
     - net

networks:
  net:
    driver: bridge
    
secrets:
  MYSQL_USER:
    file: ./config/MYSQL_USER
  MYSQL_PASSWORD:
    file: ./config/MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./config/MYSQL_ROOT_PASSWORD  


