version: '3.8'

services:
  pgsql-server:
    image: postgres:13-alpine
    restart: always
    networks:
      net:
        ipv4_address: 12.10.10.5
    env_file:
     - ./config/db_pgsql
    secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
 
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    hostname: zabbix-server
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_pgsql
     - ./config/srv
    secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
    depends_on:
     - pgsql-server
    networks:
      net:
        ipv4_address: 12.10.10.3

  zabbix-web-nginx-pgsql:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    ports:
     - "81:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - ./config/icon-sprite.svg:/usr/share/zabbix/assets/img/icon-sprite.svg
    env_file:
     - ./config/db_pgsql
     - ./config/web
    secrets:
     - POSTGRES_USER
     - POSTGRES_PASSWORD
    depends_on:
     - pgsql-server
     - zabbix-server
    networks:
      net:
        ipv4_address: 12.10.10.2

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 12.10.10.0/24
        gateway: 12.10.10.1
    
secrets:
  POSTGRES_USER:
    file: ./config/POSTGRES_USER
  POSTGRES_PASSWORD:
    file: ./config/POSTGRES_PASSWORD


