version: '3.8'

services:
  mysql-server:
    image: mysql:5.7
    restart: always
    container_name: mysql-server
    networks:
     - zabbixnet
    command:
     - mysqld
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
    volumes:
     - /home/zabbix/mysql:/var/lib/mysql:rw
    env_file:
     - ./config/db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
  
  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/srv
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    depends_on:
     - mysql-server
    networks:
     - zabbixnet

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
     - "80:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/web
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-server
    networks:
     - zabbixnet

networks:
  zabbixnet:
    driver: bridge
    
secrets:
  MYSQL_USER:
    file: ./config/MYSQL_USER
  MYSQL_PASSWORD:
    file: ./config/MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./config/MYSQL_ROOT_PASSWORD
    


