version: '3.8'

services:
  mysql-server:
    image: mysql:8.0.29
    restart: always
    container_name: mysql-server
    networks:
      net:
        ipv4_address: 12.10.10.5
    command:
     - mysqld
     - --character-set-server=utf8
     - --collation-server=utf8_bin
     - --default-authentication-plugin=mysql_native_password
     - --log_bin_trust_function_creators=1
    cap_add:
      - SYS_NICE
    volumes:
     - /home/zabbix/mysql:/var/lib/mysql:rw
    env_file:
     - ./config/db_mysql
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
 
  zabbix-java-gateway:
    image: zabbix/zabbix-java-gateway:latest
    networks:
      net:
        ipv4_address: 12.10.10.4

  zabbix-server:
    image: zabbix/zabbix-server-mysql:latest
    hostname: zabbix-server
    ports:
     - "10051:10051"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/srv
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
     - MYSQL_ROOT_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-java-gateway
     - zabbix-agent
    networks:
      net:
        ipv4_address: 12.10.10.3

  zabbix-web-nginx-mysql:
    image: zabbix/zabbix-web-nginx-mysql:latest
    ports:
     - "80:8080"
    volumes:
     - /etc/localtime:/etc/localtime:ro
    env_file:
     - ./config/db_mysql
     - ./config/web
    secrets:
     - MYSQL_USER
     - MYSQL_PASSWORD
    depends_on:
     - mysql-server
     - zabbix-server
    networks:
      net:
        ipv4_address: 12.10.10.2

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 12.10.10.0/24
        gateway: 12.10.10.1
    
secrets:
  MYSQL_USER:
    file: ./config/MYSQL_USER
  MYSQL_PASSWORD:
    file: ./config/MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./config/MYSQL_ROOT_PASSWORD  


